routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('tickets', TicketController::class)->middleware(['auth']);
Route::post('/tickets/{ticket}/assign', [TicketController::class, 'assign'])->name('tickets.assign')->middleware(['auth']);

// Route::post('/tickets/{ticket}/assign', [TicketController::class, 'assign'])->middleware('admin');

Route::resource('users', UserController::class)->middleware(['auth', 'admin']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
    ];

    public function proparty()
    {
        return $this->belongsTo(User::class, 'owner');
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {        
        $tickets = Ticket::with('proparty')->where('owner', auth()->id())->get();


        return view('tickets.index', compact('tickets'));
    // }
    //     return view('tickets.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()//: Response
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $ticket = new Ticket();
        $ticket->title = $request->input('title');
        $ticket->description = $request->input('description');
        $ticket->owner = auth()->id();

        $ticket->save();

        return redirect()->route('tickets.index');
    }

    public function assign(Ticket $ticket, Request $request)
    {
        $this->authorize('assign', $ticket);

        $user = User::find($request->input('user_id'));

        $ticket->assignTo($user);

        return redirect()->back()->with('success', 'Ticket attribué avec succès');
    }


    /**
     * Display the specified resource.
     */
    public function show(Ticket $ticket)//: Response
    {
        $supports = User::where('role', 'support')->get();


        return view('tickets.show', compact('ticket', 'supports'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Ticket $ticket)//: Response
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Ticket $ticket)//: RedirectResponse
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Ticket $ticket)//: RedirectResponse
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/tickets/index.blade.php
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
        <form method="POST" action="{{ route('tickets.store') }}">
            @csrf
            <input type="text" name="title" placeholder="Titre du ticket"
                class="my-3 block w-full border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm"
            >
            <textarea
                name="description"
                placeholder="{{ __('La description du ticket') }}"
                class="block w-full border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm"
            >{{ old('message') }}</textarea>
            <x-input-error :messages="$errors->get('message')" class="mt-2" />
            <x-primary-button class="mt-4">{{ __('Enregistrer') }}</x-primary-button>
        </form>

        <div class="mt-6 bg-white shadow-sm rounded-lg divide-y">

            @foreach ($tickets as $ticket)

                <div class="p-6 flex space-x-2">

                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600 -scale-x-100" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">

                        <path stroke-linecap="round" stroke-linejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />

                    </svg>

                    <div class="flex-1">

                        <div class="flex justify-between items-center">

                            <div>

                                <span class="text-gray-800">
                                    {{ $ticket->proparty->name }}</span>

                                <small class="ml-2 text-sm text-gray-600">{{ $ticket->created_at->format('j M Y, g:i a') }}</small>

                            </div>

                        </div>

                        
                        <p class="mt-4 text-lg text-gray-900">{{ $ticket->description }}</p>
                        <a href="{{ route('tickets.show', $ticket->id) }}">Voir</a>
                    </div>

                </div>

            @endforeach

        </div>
    </div>
</x-app-layout>

resources/views/tickets/show.blade.php
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">

        <div class="mt-6 bg-white shadow-sm rounded-lg divide-y">

                <div class="p-6 flex space-x-2">

                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600 -scale-x-100" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">

                        <path stroke-linecap="round" stroke-linejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />

                    </svg>

                    <div class="flex-1">

                        <div class="flex justify-between items-center">

                            <div>

                                <span class="text-gray-800">{{ $ticket->proparty->name }}</span>

                                <small class="ml-2 text-sm text-gray-600">{{ $ticket->created_at->format('j M Y, g:i a') }}</small>

                            </div>

                        </div>

                        <p class="mt-4 text-lg text-gray-900">{{ $ticket->description }}</p>

                    </div>

                </div>


        </div>

        @if (auth()->user()->role == 'admin')
            <form method="POST" action="{{ route('tickets.assign', $ticket) }}">
                @csrf
                <div class="form-group">
                    <label for="user_id">Attribuer à</label>
                    <select id="user_id" name="user_id" class="form-control">
                        @foreach ($supports as $support)
                            {{-- @if ($user->role == \App\Models\User::ROLE_SUPPORT) --}}
                                <option value="{{ $support->id }}">{{ $support->name }}</option>
                            {{-- @endif --}}
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Attribuer</button>
            </form>
        @endif

    </div>
</x-app-layout>